"""add targeting fields to feature_flag

Revision ID: 80938a15f7af
Revises: b6e17af0c44d
Create Date: 2025-11-25 23:45:03.696551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80938a15f7af'
down_revision: Union[str, Sequence[str], None] = 'b6e17af0c44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('environment', sa.String(), nullable=True))
    op.add_column('feature_flags', sa.Column('allowed_users', sa.JSON(), nullable=True))
    op.add_column('feature_flags', sa.Column('allowed_groups', sa.JSON(), nullable=True))
    op.add_column('feature_flags', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('feature_flags', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('feature_flags', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('feature_flags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=False)
    op.drop_column('feature_flags', 'user_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_flags', sa.Column('user_groups', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_feature_flags_name'), 'feature_flags', ['name'], unique=True)
    op.drop_column('feature_flags', 'updated_at')
    op.drop_column('feature_flags', 'created_at')
    op.drop_column('feature_flags', 'end_at')
    op.drop_column('feature_flags', 'start_at')
    op.drop_column('feature_flags', 'allowed_groups')
    op.drop_column('feature_flags', 'allowed_users')
    op.drop_column('feature_flags', 'environment')
    # ### end Alembic commands ###
